# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  database: app_development
  username: user
  password: test123
  encoding: unicode
  host: localhost
  pool: 5
test:
  adapter: postgresql
  database: app_test
  username: user
  password: test123
  encoding: unicode
  host: localhost
  pool: 5
# production:
  # <<: *default
  # database: db/production.sqlite3